### ISSUE TITLE
Estimate the work needed to assess the tool

### ISSUE THREAD

**Issue by adinuca** [NRGI/rgi-assessment-tool#597]
## Why
People at NRGI need to know what budget is needed for assessing the tool.

## What
- [ ] documents sent by Anders are read
- [ ] work needed to assess the tool is determined, documented and estimated
- [ ] estimates are communicated to Anders

**Comment by adinuca** [comment]
This has been done at the beginning of the year
